before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates: ["jaymedh/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates: ["jaymedh/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: jaymedh/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - jaymedh/{{ .ProjectName }}:{{ .Version }}-amd64
      - jaymedh/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: jaymedh/{{ .ProjectName }}:latest
    image_templates:
      - jaymedh/{{ .ProjectName }}:{{ .Version }}-amd64
      - jaymedh/{{ .ProjectName }}:{{ .Version }}-arm64v8
