{
 "title": "FRITZ!Box Smarthome",
 "description": "FRITZ!Box Smarthome exporter dashboard ",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "switch_name",
    "query": "label_values(fritzbox_switch_state,device_name)"
   },
   {
    "name": "thermostat_name",
    "query": {
     "query": "label_values(fritzbox_device_info{device_type=\"FRITZ!DECT 300\"},device_name)"
    }
   },
   { "name": "power_Cost", "query": "0.52" }
  ]
 },
 "panels": [
  {
   "title": "Devices present",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(fritzbox_device_present == 1)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "fritzbox_temperature", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Devices known",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(fritzbox_device_present)" }
   ]
  },
  { "title": "Thermostat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Thermostat Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fritzbox_thermostat_battery_charge_level",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "State $thermostat_name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "repeat": "thermostat_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritzbox_thermostat_state{device_name=\"$thermostat_name\"}"
    }
   ]
  },
  {
   "title": "Open Window: $thermostat_name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "repeat": "thermostat_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritzbox_thermostat_window_open{device_name=\"$thermostat_name\"}"
    }
   ]
  },
  {
   "title": "Switch: $switch_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "switch_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritzbox_switch_state{device_name=\"$switch_name\"}"
    }
   ]
  },
  {
   "title": "Power meter",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(fritzbox_energy{device_name=\"$switch_name\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 23 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": " fritzbox_power{device_name=\"$switch_name\"}",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Energy total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritzbox_energy{device_name=\"$switch_name\"}"
    }
   ]
  },
  {
   "title": "Power cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(fritzbox_energy{device_name=\"$switch_name\"}[$__range])/1000)*$power_Cost",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}